site_name: Togother Docs
site_description: 一起看文档
site_author: pwxiao

theme:
  name: material
  language: zh
  font:
    text: Noto Sans SC
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: white
      accent: white
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

nav:
  - 首页: index.md
  - 下载: download.md
  - 指南: 
    - 快速开始: guide/getting-started.md
    - 导入视频源: guide/import_source.md
    - 网盘功能:
      - 夸克网盘: guide/quark_netdisk.md
      - WebDAV/Alist: guide/webdav_alist.md
  - 帮助中心:
    - 常见问题: help.md
    - 搜索引擎帮助: search_engine_help.md
  - 法律条款:
    - 用户协议: terms.md
    - 隐私政策: privacy.md
  - 更新历史: changelog.md
  - 支持: support.md

